media:
  input: src/uploads
  output: /uploads
content:
  - name: posts
    label: Posts
    path: src/_content/_collections/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: published
        label: Published
        type: boolean
        default: false
      - name: summary
        label: Summary
        type: text
      - name: post
        label: Post
        type: rich-text
      - name: tags
        hidden: true
        label: Tags
        default: blog
  - name: fakestagram
    label: Fakestagram
    path: src/_content/_collections/fakestagram
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
      - name: photo
        label: Photo
        type: image
      - name: alt
        label: Alt text
        type: string
      - name: caption
        label: Caption
        type: string
      - name: date
        label: Date
        type: date
        time: true
      - name: published
        label: Published
        type: boolean
        default: true
  - name: bookmarks
    label: Bookmarks
    path: src/_content/_collections/bookmarks
    type: collection
    fields: 
      - name: title
        label: Title 
        type: string
      - name: date
        label: Date
        type: date
      - name: link
        label: Link
        type: string
      - name: description
        label: description
        type: text
      - name: type
        label: Type
        type: select 
        options:
          multiple: true
          values: [ Web Development, Website, Social Media, Art, Creative Coding, Book Binding, Article, Misc, Video Games, Home Lab, Accessibility ]
  - name: goodreads
    label: Goodreads
    path: src/_content/_collections/goodreads
    type: collection
    fields:
      - name: title
        label: Title 
        type: string
      - name: author
        label: Author
        type: string
      - name: cover
        label: Cover
        type: string
      - name: date
        label: Date Read
        type: date
        options:  
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss.000'Z'
      - name: category
        label: Category
        type: select
        options:  
          values: [ read, dnf ]
  - name: letterboxd
    label: Letterboxd
    path: src/_content/_collections/letterboxd
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
      - name: poster
        label: Poster
        type: string
      - name: link
        label: Link
        type: string
        hidden: true
      - name: review
        label: Review
        type: string
      - name: date
        label: Date
        type: date
        options:  
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss.000'Z'
      - name: id
        label: ID
        type: string
        hidden: true
  - name: strava
    label: Strava
    path: src/_content/_collections/strava
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: id
        label: ID
        types: string
        hidden: true
      - name: link
        label: Link
        types: string
        hidden: true
      - name: date
        label: Date
        types: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss.000'Z'
      - name: rideDate
        label: Ride Date
        types: string
        hidden: true
      - name: pubDate
        label: Publish Date
        types: string
        hidden: true
      - name: type
        label: Type
        type: select
        options:  
          values: [ ride, walk ]
      - name: distance
        label: Distance
        types: string
      - name: elevation
        label: Elevation
        types: string
      - name: time
        label: Time
        types: string
      - name: speed
        label: Speed
        types: string
      - name: tags
        label: Tags
        type: select
        options:  
          values: [ kuzco-tracker ]