content:
  - name: posts
    label: Posts
    path: src/_content/_collections/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: published
        label: Published
        type: boolean
        default: false
      - name: post
        label: Post
        type: rich-text
      - name: tags
        hidden: true
        label: Tags
        default: blog
