media:
  input: src/uploads
  output: /uploads
content:
  - name: posts
    label: Posts
    path: src/_content/_collections/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: published
        label: Published
        type: boolean
        default: false
      - name: summary
        label: Summary
        type: text
      - name: post
        label: Post
        type: rich-text
      - name: tags
        hidden: true
        label: Tags
        default: blog
  - name: fakestagram
    label: Fakestagram
    path: src/_content/_collections/fakestagram
    type: collection
    fields: 
      - name: published
        label: Published
        type: boolean
        default: true
      - name: alt
        label: Alt text
      - name: photo
        label: Photo
        type: image
