media:
  input: src/uploads
  output: /uploads
content:
  - name: posts
    label: Posts
    path: src/_content/_collections/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: published
        label: Published
        type: boolean
        default: false
      - name: summary
        label: Summary
        type: text
      - name: post
        label: Post
        type: rich-text
      - name: tags
        hidden: true
        label: Tags
        default: blog
  - name: fakestagram
    label: Fakestagram
    path: src/_content/_collections/fakestagram
    type: collection
    fields: 
      - name: title
        label: Title
        type: string
      - name: photo
        label: Photo
        type: image
      - name: alt
        label: Alt text
        type: string
      - name: caption
        label: Caption
        type: string
      - name: date
        label: Date
        type: date
        time: true
      - name: published
        label: Published
        type: boolean
        default: true
  - name: bookmarks
    label: Bookmarks
    path: src/_content/_collections/bookmarks
    type: collection
    fields: 
      - name: title
        label: Title 
        type: string
      - name: date
        label: Date
        type: date
      - name: link
        label: Link
        type: string
      - name: description
        label: description
        type: text
      - name: type
        label: Type
        type: select 
        options:
          multiple: true
          values: [ Web Development, Website, Social Media, Art, Creative Coding, Book Binding, Article, Misc, Video Games, Home Lab, Accessibility ]
  - name: goodreads
    label: Goodreads
    path: src/_content/_collections/goodreads
    type: collection
    fields:
      - name: title
        label: Title 
        type: string
      - name: author
        label: Author
        type: string
      - name: cover
        label: Cover
        type: string
      - name: date
        label: Date Read
        type: date
        options:  
          time: true
          format: yyyy-MM-ddTHH:mm:ssZ