content:
  - name: posts
    label: Posts
    path: src/_content/_collections/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: post
        label: Post
        type: rich-text
