[[plugins]]
package = "netlify-plugin-cache, @netlify/plugin-lighthouse"

  [plugins.inputs]
  paths = [
    "_site/img/processed",
    ".cache"
  ]
  
  [plugins.inputs.audits]
  output_path = "reports/lighthouse.html"