[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
    paths = [
      "_site/img/processed",
      ".cache"
    ]

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
